name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity quiet
    - name: Install dependencies
      run: |
        dotnet add Infrastructure/Infrastructure.csproj package Dapper --version 2.0.9
        dotnet add API/API.csproj package AutoMapper.Extensions.Microsoft.DependencyInjection --version 8.1.1
        dotnet add API/API.csproj package IdentityServer4 --version 4.1.2
        dotnet add API/API.csproj package IdentityServer4.AccessTokenValidation --version 3.0.1
        dotnet add API/API.csproj package Microsoft.AspNetCore.Authentication.JwtBearer --version 5.0.7